### ISSUE TITLE
Emotion cache key conflicts

### ISSUE THREAD

**Issue by avele** [sajari/sdk-react#605]
Hello

Please provide a key for "@emotion/cache", otherwise it conflicts with the emotion package used in an application. See screenshot below:

![2021-08-27 00 06 12](https://user-images.githubusercontent.com/34437766/131036017-7e68a2ce-d888-449f-9449-16c0e9398bce.jpg)

**Comment by zlatanpham** [comment]
Hi @avele, thanks for reporting the issue. We've included the fix in the latest release.
