### ISSUE TITLE
Results component `resultTemplate` quotes rendering

### ISSUE THREAD

**Issue by avele** [sajari/sdk-react#618]
When using `resultTemplate` quotation marks in fields data are rendered as `&quot;` instead of `"`

**Comment by tuanddd** [comment]
HI @avele can you try this? https://github.com/lukeed/tempura/blob/de8e4ae40270dd13ec0a439bc909763842ec7caa/docs/syntax.md#raw-values

**Comment by avele** [comment]
Thanks, @tuanddd triple curly brackets work well.
